default genpack
prompt 1
timeout 10
label genpack
    kernel /kernel
    initrd /initramfs
    fdt /imx95-catalina-gw92xx-0x.dtb
    append root=systemimg:auto console=ttyLP0,115200 panic=30 systemd.firstboot=0
label genpack-transient
    kernel /kernel
    initrd /initramfs
    fdt /imx95-catalina-gw92xx-0x.dtb
    append root=systemimg:auto console=ttyLP0,115200 panic=30 systemd.firstboot=0 genpack.transient=1
