import os,glob,logging

default_network_config = """# generated by genpack-init script
[Match]
Name=eth* en* host*
[Network]
DHCP=yes
LLMNR=yes
"""

def is_avahi_enabled():
    return os.path.exists("/etc/systemd/system/multi-user.target.wants/avahi-daemon.service")

def configure():
    network_dir = "/etc/systemd/network"
    if len(glob.glob(os.path.join(network_dir, "*"))) > 0:
        logging.debug("There is something under /etc/systemd/network. default config is omitted")
        return
    #else
    with open(os.path.join(network_dir, "50-default.network"), "w") as f:
        f.write(default_network_config)
        # set MulticastDNS to 'no' if avahi is enabled
        f.write("MulticastDNS=%s\n" % ("no" if is_avahi_enabled() else "yes"))
    logging.info("Default network config file generated as /etc/systemd/network/50-default.network")
