import logging,itertools
from genpack_init import root_path
default_network_config = """# generated by genpack-init script
[Match]
Type=ether
#Exclude SR-IOV VF
Name=!en*v*
[Network]
DHCP=yes
LLMNR=yes
"""

def is_avahi_enabled():
    return root_path("/etc/systemd/system/multi-user.target.wants/avahi-daemon.service").exists()

def configure():
    network_dir = root_path("/etc/systemd/network")
    network_dir.mkdir(parents=True, exist_ok=True)
    for config in itertools.chain(network_dir.glob("*.network"), network_dir.glob("*.netdev")):
        logging.debug("There is something under /etc/systemd/network. default config is omitted")
        return
    #else
    with open(network_dir.joinpath("50-default.network"), "w") as f:
        f.write(default_network_config)
        # set MulticastDNS to 'no' if avahi is enabled
        f.write("MulticastDNS=%s\n" % ("no" if is_avahi_enabled() else "yes"))
    logging.info("Default network config file generated as /etc/systemd/network/50-default.network")

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    configure()